{
  description = "NixOS dev VM for flexwm, bootable on macOS (QEMU + Hypervisor.framework)";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { self, nixpkgs }:
    let
      guestSystem = "aarch64-linux";
      hostSystem = "aarch64-darwin";
      hostPkgs = nixpkgs.legacyPackages.${hostSystem};

      nixos = nixpkgs.lib.nixosSystem {
        system = guestSystem;
        modules = [
          ./configuration.nix
          # The one line that makes this a Mac-native VM: NixOS builds the
          # launcher script with these pkgs, so `system.build.vm` is an
          # aarch64-darwin derivation that runs qemu directly on the host.
          { virtualisation.host.pkgs = hostPkgs; }
        ];
      };

      # Generated by NixOS: creates the disk on first run, packs the store into
      # an erofs image, boots the kernel directly under HVF.
      runner = nixos.config.system.build.vm;

      # run-vm.sh only decides *where* state lives and what gets shared in;
      # everything else is the generated runner's job.
      runVm = hostPkgs.writeShellApplication {
        name = "flexwm-vm";
        runtimeInputs = [ hostPkgs.qemu ];
        text = ''
          FLEXWM_VM_RUNNER=${nixpkgs.lib.getExe runner}
          export FLEXWM_VM_RUNNER
        ''
        + builtins.readFile ./run-vm.sh;
      };
    in
    {
      nixosConfigurations.flexwm-vm = nixos;

      packages.${hostSystem} = {
        default = runVm;
        vm = runVm;
        # The raw generated launcher, if you want to drive it yourself.
        inherit runner;
        # The Linux builder that builds the guest closure; see linux-builder.sh.
        # The stock 20G disk is tight for a VM this size, so ask for more. Only
        # applies when the builder's disk is created, i.e. delete
        # ~/.local/state/nix-linux-builder/*.qcow2 to pick it up.
        linux-builder = hostPkgs.darwin.linux-builder.override {
          # Only host-side settings belong here. `diskSize` affects the
          # launcher script (an aarch64-darwin derivation), so it stays
          # substitutable. Anything touching the *guest* -- nix.settings,
          # packages, services -- makes the builder's own closure need a Linux
          # builder to build, which deadlocks when the builder is down. Fix
          # the builder's download behaviour from the host instead, with
          # builders-use-substitutes (see README).
          modules = [ { virtualisation.darwin-builder.diskSize = 60 * 1024; } ];
        };
      };

      # Built on the Linux builder, then copied back to the Mac, which is where
      # the store image is packed from.
      packages.${guestSystem}.toplevel = nixos.config.system.build.toplevel;

      apps.${hostSystem}.default = {
        type = "app";
        program = "${runVm}/bin/flexwm-vm";
      };
    };
}
