//! The procedurally-drawn cursor shapes, and which named shape each
//! [`CursorIcon`] maps onto.
//!
//! # Why these are drawn rather than loaded
//!
//! Same reason `cursor.rs`'s arrow is: every pixel here is generated by this
//! file's own arithmetic, so nothing in the tree is a copy of an xcursor
//! theme's asset. niri's cursor assets are GPL and Adwaita's are not
//! MIT-clean (see `CLAUDE.md`'s license note), and this project has no
//! MIT-clean theme to load -- so a compositor that wants to answer
//! `wp_cursor_shape_device_v1.set_shape` with anything other than one
//! shape for every request has to draw the shapes itself. That is what this
//! module is: line art, not a theme.
//!
//! It is also why the set is deliberately small. Ten shapes cover what a
//! session actually distinguishes by feel -- an I-beam over text, a resize
//! arrow on an edge, a crosshair, a "no" -- and every [`CursorIcon`] outside
//! that set falls back to [`Shape::Arrow`] rather than getting a
//! hand-drawn near-duplicate nobody can tell apart at 16 pixels.
//!
//! # How a shape is built
//!
//! Two passes, both over a `size x size` grid:
//!
//! 1. **Coverage.** Each shape stamps its strokes and arrowheads into a
//!    boolean mask through the primitives below ([`stroke_line`],
//!    [`fill_triangle`], [`stroke_circle`]). Nothing here knows about color.
//! 2. **Ink.** [`ink`] turns that mask into `Argb8888` pixels: a covered
//!    cell is `fill`, an uncovered cell that touches a covered one (8-way)
//!    is `outline`, everything else is transparent.
//!
//! The outline therefore sits *outside* each stroke, unlike `cursor.rs`'s
//! arrow, whose outline is drawn inside its own silhouette. That difference
//! is deliberate and not worth unifying: the arrow is a solid body several
//! pixels across, so an interior outline costs it nothing, while every shape
//! here is line art one or two pixels thick -- an interior outline would
//! consume the entire stroke at the default 16px size and leave a cursor
//! made of nothing but outline. Drawing outward keeps a thin stroke legible
//! against content of a similar color, which is the only thing the outline is
//! for.
//!
//! All of this runs exactly once per shape, at startup, from
//! [`Cursor::new`](super::Cursor::new) -- never per frame and never per
//! `set_shape` request, which is an array index into buffers built here.

use smithay::input::pointer::CursorIcon;
use smithay::utils::{Logical, Point};

#[cfg(test)]
mod tests;

/// One drawable cursor shape.
///
/// Not a mirror of [`CursorIcon`] -- see [`Shape::for_icon`] for the mapping
/// and this module's doc for why the set is this small.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Shape {
    /// The pointer itself: `cursor.rs`'s filled triangle, and the answer for
    /// every icon this module does not draw something specific for.
    Arrow,
    /// An I-beam, for text entry.
    Text,
    /// The I-beam turned on its side, for vertical text.
    VerticalText,
    /// A plus, for precise picking.
    Crosshair,
    /// A vertical double-headed arrow.
    ResizeNs,
    /// A horizontal double-headed arrow.
    ResizeEw,
    /// A double-headed arrow from bottom-left to top-right.
    ResizeNesw,
    /// A double-headed arrow from top-left to bottom-right.
    ResizeNwse,
    /// A four-headed arrow: move, grab, scroll in any direction.
    Move,
    /// A circle with a slash through it.
    NotAllowed,
}

impl Shape {
    /// Every shape, in the order [`Shape::index`] numbers them.
    ///
    /// The one place that order is written down -- [`Cursor`](super::Cursor)
    /// builds its buffers by walking this, and reads them back by
    /// [`Shape::index`], so the two cannot drift apart.
    pub const ALL: [Shape; Self::COUNT] = [
        Shape::Arrow,
        Shape::Text,
        Shape::VerticalText,
        Shape::Crosshair,
        Shape::ResizeNs,
        Shape::ResizeEw,
        Shape::ResizeNesw,
        Shape::ResizeNwse,
        Shape::Move,
        Shape::NotAllowed,
    ];

    /// How many shapes there are, i.e. how many bitmaps
    /// [`Cursor`](super::Cursor) holds.
    pub const COUNT: usize = 10;

    /// This shape's slot in [`Shape::ALL`].
    pub fn index(self) -> usize {
        match self {
            Shape::Arrow => 0,
            Shape::Text => 1,
            Shape::VerticalText => 2,
            Shape::Crosshair => 3,
            Shape::ResizeNs => 4,
            Shape::ResizeEw => 5,
            Shape::ResizeNesw => 6,
            Shape::ResizeNwse => 7,
            Shape::Move => 8,
            Shape::NotAllowed => 9,
        }
    }

    /// The shape drawn for a client's requested [`CursorIcon`].
    ///
    /// Total by construction -- a `_` arm, not an enumeration of the rest:
    /// [`CursorIcon`] is a non-exhaustive upstream enum, so a version bump
    /// that adds an icon must keep compiling and must show *something*
    /// rather than nothing. [`Shape::Arrow`] is that something.
    ///
    /// The groupings are the ones a user can actually distinguish:
    /// `NResize`/`SResize`/`NsResize`/`RowResize` all mean "this edge moves
    /// up and down", and drawing one arrow with a head at each end says that
    /// more clearly than half an arrow would. `Grab`/`Grabbing`/`AllScroll`
    /// share [`Shape::Move`] for the same reason -- an open and a closed hand
    /// are not distinguishable as line art at 16 pixels, and both mean "this
    /// thing is being dragged".
    pub fn for_icon(icon: CursorIcon) -> Shape {
        match icon {
            CursorIcon::Text => Shape::Text,
            CursorIcon::VerticalText => Shape::VerticalText,
            CursorIcon::Crosshair | CursorIcon::Cell => Shape::Crosshair,
            CursorIcon::NResize
            | CursorIcon::SResize
            | CursorIcon::NsResize
            | CursorIcon::RowResize => Shape::ResizeNs,
            CursorIcon::EResize
            | CursorIcon::WResize
            | CursorIcon::EwResize
            | CursorIcon::ColResize => Shape::ResizeEw,
            CursorIcon::NeResize | CursorIcon::SwResize | CursorIcon::NeswResize => {
                Shape::ResizeNesw
            }
            CursorIcon::NwResize | CursorIcon::SeResize | CursorIcon::NwseResize => {
                Shape::ResizeNwse
            }
            CursorIcon::Move
            | CursorIcon::AllScroll
            | CursorIcon::AllResize
            | CursorIcon::Grab
            | CursorIcon::Grabbing => Shape::Move,
            CursorIcon::NotAllowed | CursorIcon::NoDrop => Shape::NotAllowed,
            _ => Shape::Arrow,
        }
    }

    /// The point within this shape's bitmap that lines up with the pointer's
    /// actual location.
    ///
    /// The arrow points at its own top-left corner, which is where the
    /// pointer is. Every other shape here is symmetric about its middle and
    /// means "the thing under the middle of me", so its hotspot is the
    /// center -- an I-beam anchored at a corner would put the text caret half
    /// a cursor away from where the user is pointing.
    ///
    /// `size` is the bitmap's edge length, already clamped by
    /// [`Cursor::new`](super::Cursor::new).
    pub fn hotspot(self, size: i32) -> Point<i32, Logical> {
        match self {
            Shape::Arrow => (0, 0).into(),
            _ => (size / 2, size / 2).into(),
        }
    }
}

/// Draws `shape` into a fresh `size * size * 4` byte `Argb8888` buffer.
///
/// `fill` and `outline` are single premultiplied little-endian `Argb8888`
/// pixels (`[B, G, R, A]`), the same layout `cursor.rs`'s arrow uses and the
/// same one the render path scans out -- see that module's doc.
///
/// [`Shape::Arrow`] is *not* handled here: it is `cursor.rs`'s own
/// `generate_bitmap`, kept byte-identical to what it has always produced (see
/// this module's doc on the two outline styles). Passing it returns an empty
/// mask, i.e. a fully transparent bitmap, which is why
/// [`Cursor::new`](super::Cursor::new) routes the arrow to its own generator
/// instead of calling this. That is asserted in this module's tests rather
/// than left as a trap.
pub fn generate(shape: Shape, size: i32, fill: [u8; 4], outline: [u8; 4]) -> Vec<u8> {
    let mut mask = vec![false; (size * size) as usize];
    draw(shape, size, &mut mask);
    ink(&mask, size, fill, outline)
}

/// Stamps `shape`'s coverage into `mask`.
///
/// Every dimension is a fraction of `size` so a shape at 4px and the same
/// shape at 256px are the same drawing, not the same pixel count -- then
/// every one of those fractions is clamped into the *safe box*: the
/// `1..=size - 2` band in both axes, one cell in from the bitmap's edge.
///
/// That clamp is what makes [`ink`]'s outline pass complete rather than
/// clipped. A stroke flush against the bitmap edge has nowhere to put the
/// outline on that side, so it would show its fill colour directly against
/// whatever is under the cursor there -- exactly the illegibility the outline
/// exists to prevent. The fractions alone are not enough to guarantee it:
/// at `Appearance::MIN_CURSOR_SIZE` (4) the safe box is 2x2, and every
/// measurement below -- margin, serif, arrowhead depth and base -- rounds
/// down into it or collapses to zero. A 4px cursor is a legible dot rather
/// than a legible drawing, which is the honest outcome at that size; nothing
/// here pretends otherwise, and the tests assert the safe box holds at every
/// size a config can ask for.
fn draw(shape: Shape, size: i32, mask: &mut [bool]) {
    // The safe box: no shape may cover a cell outside it (see above).
    let lo = 1;
    let hi = size - 2;
    // The stroke width every line in this module is drawn at: one cell up to
    // 23px, scaling from there, so a large cursor is a larger drawing rather
    // than the same hairline on a bigger grid. Never wider than the safe box.
    let stroke = (size / 12).max(1).min(hi - lo + 1);
    let center = size / 2;
    // The near and far ends of every stroke that spans the bitmap, mirrored
    // about its middle and inside the safe box.
    let near = (size / 8).max(1).max(lo);
    let far = (size - 1 - (size / 8).max(1)).min(hi);
    // How far an arrowhead reaches back from its own tip, and half its width
    // there -- both clamped so the head stays inside the safe box however
    // small the bitmap is.
    let head = (size / 4).max(2).min(hi - near).min(far - lo).max(0);
    let half_base = (size / 7).max(1).min(center - lo).min(hi - center).max(0);
    // Half the width of an I-beam's serifs, same clamp as `half_base`.
    let serif = (size / 8).max(1).min(center - lo).min(hi - center).max(0);

    match shape {
        // Drawn by `cursor.rs::generate_bitmap`, not here -- see this
        // function's own doc.
        Shape::Arrow => {}
        Shape::Text => {
            stroke_line(mask, size, (center, near), (center, far), stroke);
            stroke_line(
                mask,
                size,
                (center - serif, near),
                (center + serif, near),
                stroke,
            );
            stroke_line(
                mask,
                size,
                (center - serif, far),
                (center + serif, far),
                stroke,
            );
        }
        Shape::VerticalText => {
            stroke_line(mask, size, (near, center), (far, center), stroke);
            stroke_line(
                mask,
                size,
                (near, center - serif),
                (near, center + serif),
                stroke,
            );
            stroke_line(
                mask,
                size,
                (far, center - serif),
                (far, center + serif),
                stroke,
            );
        }
        Shape::Crosshair => {
            stroke_line(mask, size, (center, near), (center, far), stroke);
            stroke_line(mask, size, (near, center), (far, center), stroke);
        }
        Shape::ResizeNs => {
            stroke_line(mask, size, (center, near), (center, far), stroke);
            arrowhead_v(mask, size, center, near, head, half_base, true);
            arrowhead_v(mask, size, center, far, head, half_base, false);
        }
        Shape::ResizeEw => {
            stroke_line(mask, size, (near, center), (far, center), stroke);
            arrowhead_h(mask, size, near, center, head, half_base, true);
            arrowhead_h(mask, size, far, center, head, half_base, false);
        }
        Shape::ResizeNwse => {
            stroke_line(mask, size, (near, near), (far, far), stroke);
            // A right triangle with its corner at the tip and its legs along
            // the two axes: the diagonal equivalent of the flat arrowheads
            // above, and the only arrowhead shape that stays symmetric about
            // the 45-degree shaft without any trigonometry.
            fill_triangle(
                mask,
                size,
                (near, near),
                (near + head, near),
                (near, near + head),
            );
            fill_triangle(mask, size, (far, far), (far - head, far), (far, far - head));
        }
        Shape::ResizeNesw => {
            stroke_line(mask, size, (far, near), (near, far), stroke);
            fill_triangle(
                mask,
                size,
                (far, near),
                (far - head, near),
                (far, near + head),
            );
            fill_triangle(
                mask,
                size,
                (near, far),
                (near + head, far),
                (near, far - head),
            );
        }
        Shape::Move => {
            stroke_line(mask, size, (center, near), (center, far), stroke);
            stroke_line(mask, size, (near, center), (far, center), stroke);
            arrowhead_v(mask, size, center, near, head, half_base, true);
            arrowhead_v(mask, size, center, far, head, half_base, false);
            arrowhead_h(mask, size, near, center, head, half_base, true);
            arrowhead_h(mask, size, far, center, head, half_base, false);
        }
        Shape::NotAllowed => {
            // `far - center` rather than `size / 2 - margin`: both are the
            // radius that puts the ring inside the safe box, but this one is
            // written in terms of the same `far` the slash below is measured
            // from, so the slash cannot outgrow its own circle at any size.
            let radius = (far - center).max(0);
            stroke_circle(mask, size, center, center, radius, stroke);
            // The slash runs corner to corner of the circle's bounding box at
            // 45 degrees, which is where a real "no entry" sign puts it.
            let reach = radius * 7 / 10;
            stroke_line(
                mask,
                size,
                (center - reach, center + reach),
                (center + reach, center - reach),
                stroke,
            );
        }
    }
}

/// An arrowhead whose tip is at `(x, tip_y)`, pointing up when `up`, down
/// otherwise. `depth` is how far it reaches back from the tip and `half_base`
/// half its width there.
fn arrowhead_v(
    mask: &mut [bool],
    size: i32,
    x: i32,
    tip_y: i32,
    depth: i32,
    half_base: i32,
    up: bool,
) {
    let base_y = if up { tip_y + depth } else { tip_y - depth };
    fill_triangle(
        mask,
        size,
        (x, tip_y),
        (x - half_base, base_y),
        (x + half_base, base_y),
    );
}

/// [`arrowhead_v`] turned on its side: tip at `(tip_x, y)`, pointing left when
/// `left`, right otherwise.
fn arrowhead_h(
    mask: &mut [bool],
    size: i32,
    tip_x: i32,
    y: i32,
    depth: i32,
    half_base: i32,
    left: bool,
) {
    let base_x = if left { tip_x + depth } else { tip_x - depth };
    fill_triangle(
        mask,
        size,
        (tip_x, y),
        (base_x, y - half_base),
        (base_x, y + half_base),
    );
}

/// Marks one cell, ignoring anything outside the bitmap.
///
/// Every primitive here goes through this rather than checking its own
/// bounds, so a shape whose arithmetic reaches off the grid at some size
/// draws a clipped shape instead of panicking (debug) or corrupting the
/// neighboring row (release). The shapes above are written not to need it,
/// which is what the tests assert; this is the backstop that keeps a future
/// one from being a crash.
fn plot(mask: &mut [bool], size: i32, x: i32, y: i32) {
    if x < 0 || y < 0 || x >= size || y >= size {
        return;
    }
    mask[(y * size + x) as usize] = true;
}

/// A line from `a` to `b`, `thickness` cells wide.
///
/// A DDA walk stamping a `thickness x thickness` square at each step: the
/// squares overlap on a diagonal, which is exactly what makes a 45-degree
/// stroke the same visual weight as a horizontal one instead of a thinner
/// dotted trail.
fn stroke_line(mask: &mut [bool], size: i32, a: (i32, i32), b: (i32, i32), thickness: i32) {
    let (x0, y0) = a;
    let (x1, y1) = b;
    let dx = x1 - x0;
    let dy = y1 - y0;
    let steps = dx.abs().max(dy.abs()).max(1);
    // Half the stamp, biased so an odd thickness is centered on the line and
    // an even one leans the same way at both ends.
    let back = (thickness - 1) / 2;
    for step in 0..=steps {
        // Rounded rather than truncated (`+ steps / 2`): truncation biases
        // every interior point of a shallow diagonal toward its start, which
        // shows up as a visible kink at the midpoint of a long stroke.
        let x = x0 + (dx * step + steps / 2 * dx.signum()) / steps;
        let y = y0 + (dy * step + steps / 2 * dy.signum()) / steps;
        for oy in 0..thickness {
            for ox in 0..thickness {
                plot(mask, size, x - back + ox, y - back + oy);
            }
        }
    }
}

/// A filled triangle, by the standard edge-function test over its own
/// bounding box.
///
/// The `>= 0` on all three edges (rather than a winding-order-sensitive
/// test) is what lets the callers above pass their vertices in whatever order
/// reads most clearly, without a clockwise/counter-clockwise convention to
/// get wrong; the `|| <= 0` covers the other winding.
fn fill_triangle(mask: &mut [bool], size: i32, a: (i32, i32), b: (i32, i32), c: (i32, i32)) {
    let min_x = a.0.min(b.0).min(c.0).max(0);
    let max_x = a.0.max(b.0).max(c.0).min(size - 1);
    let min_y = a.1.min(b.1).min(c.1).max(0);
    let max_y = a.1.max(b.1).max(c.1).min(size - 1);
    // Every coordinate here is bounded by the bitmap's edge length, which
    // `Appearance::MAX_CURSOR_SIZE` caps at 256, so these cross products
    // cannot come close to overflowing.
    let edge = |p: (i32, i32), q: (i32, i32), x: i32, y: i32| {
        (q.0 - p.0) * (y - p.1) - (q.1 - p.1) * (x - p.0)
    };
    for y in min_y..=max_y {
        for x in min_x..=max_x {
            let ab = edge(a, b, x, y);
            let bc = edge(b, c, x, y);
            let ca = edge(c, a, x, y);
            let inside = (ab >= 0 && bc >= 0 && ca >= 0) || (ab <= 0 && bc <= 0 && ca <= 0);
            if inside {
                plot(mask, size, x, y);
            }
        }
    }
}

/// A circle outline of radius `radius` centred on `(cx, cy)`, `thickness`
/// cells wide.
///
/// A distance test over the ring's bounding box rather than a midpoint
/// walk: at these sizes the box is a few hundred cells at most, and a
/// squared-distance band gives a uniform-width ring without the
/// double-plotted cells a Bresenham circle leaves at its octant seams.
fn stroke_circle(mask: &mut [bool], size: i32, cx: i32, cy: i32, radius: i32, thickness: i32) {
    if radius <= 0 {
        return;
    }
    let outer = radius;
    let inner = (radius - thickness).max(0);
    let (outer_sq, inner_sq) = (outer * outer, inner * inner);
    for y in (cy - outer).max(0)..=(cy + outer).min(size - 1) {
        for x in (cx - outer).max(0)..=(cx + outer).min(size - 1) {
            let (dx, dy) = (x - cx, y - cy);
            let distance_sq = dx * dx + dy * dy;
            if distance_sq <= outer_sq && distance_sq >= inner_sq {
                plot(mask, size, x, y);
            }
        }
    }
}

/// Turns a coverage mask into `Argb8888` pixels: covered cells get `fill`,
/// uncovered cells touching a covered one (8-way) get `outline`, the rest
/// stay transparent.
///
/// The 8-way neighborhood, not 4-way: a 4-way dilation leaves the diagonal
/// corners of a stroke bare, so a 45-degree arrow would show its fill colour
/// directly against the content on two of its four sides -- which is the one
/// thing the outline exists to prevent.
fn ink(mask: &[bool], size: i32, fill: [u8; 4], outline: [u8; 4]) -> Vec<u8> {
    let transparent = [0u8; 4];
    let mut pixels = vec![0u8; (size * size * 4) as usize];
    let covered =
        |x: i32, y: i32| x >= 0 && y >= 0 && x < size && y < size && mask[(y * size + x) as usize];
    for y in 0..size {
        for x in 0..size {
            let pixel = if covered(x, y) {
                fill
            } else if (-1..=1).any(|oy| (-1..=1).any(|ox| covered(x + ox, y + oy))) {
                outline
            } else {
                transparent
            };
            let idx = ((y * size + x) * 4) as usize;
            pixels[idx..idx + 4].copy_from_slice(&pixel);
        }
    }
    pixels
}
