#!/bin/sh
# build-deb.sh: build the three scoot .debs from a source tree.
#
# Usage: packaging/deb/build-deb.sh --source DIR --out DIR [--revision N]
#
# --source is a clean checkout or a `scripts/vendor-release.sh` staged
# `source/` tree (the same layout the release tarball unpacks to, so
# after the first release this builds the published tarball with the
# same command). The build runs `cargo build --release --locked
# --offline`, so the tree must be vendored (or the registry warm);
# `CARGO_NET_OFFLINE=true` is exported to make any network touch fail.
# --out receives `scoot_<ver>_<arch>.deb` and friends.
#
# Per package the script: builds the crate, derives Depends from
# `dpkg-shlibdeps -O` over the staged binaries (checked against the
# ldd-derived allow-list in deb-meta.py -- a new or renamed system
# library fails here), renders DEBIAN/control from the crate manifests
# (no version is remembered anywhere), stages the installed files (the
# same set as packaging/arch: the session entry, the bar's user unit,
# licenses including the deny-generated inventory, no writes to a user
# config), and runs `dpkg-deb --build`.
#
# Needs: cargo (a toolchain past the workspace rust-version floor --
# bookworm's own rustc is too old, so the container installs the pinned
# rustup toolchain, the same one release.yml uses), dpkg-dev
# (dpkg-shlibdeps), dpkg-deb, python3. THIRD-PARTY-LICENSES comes from
# the source tree when staged (vendor-release.sh generates it) and from
# `cargo deny list` otherwise.
set -eu

SOURCE=""
OUT=""
REVISION="1"

while [ $# -gt 0 ]; do
    case "$1" in
        --source) SOURCE="$2"; shift 2 ;;
        --out) OUT="$2"; shift 2 ;;
        --revision) REVISION="$2"; shift 2 ;;
        -h|--help)
            echo "usage: packaging/deb/build-deb.sh --source DIR --out DIR [--revision N]"
            exit 0 ;;
        *) echo "build-deb.sh: unknown flag $1" >&2; exit 2 ;;
    esac
done

if [ -z "$SOURCE" ] || [ -z "$OUT" ]; then
    echo "build-deb.sh: --source and --out are required" >&2
    exit 2
fi

for tool in cargo dpkg-deb dpkg-shlibdeps python3; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "build-deb.sh: need '$tool' on PATH" >&2
        exit 2
    fi
done

HERE=$(dirname "$0")
META="$HERE/deb-meta.py"

if command -v dpkg >/dev/null 2>&1; then
    ARCH=$(dpkg --print-architecture)
else
    case "$(uname -m)" in
        x86_64) ARCH=amd64 ;;
        aarch64) ARCH=arm64 ;;
        *) echo "build-deb.sh: unknown architecture $(uname -m)" >&2; exit 2 ;;
    esac
fi
echo "--- architecture: $ARCH"

if [ -f "$SOURCE/THIRD-PARTY-LICENSES" ]; then
    echo "--- THIRD-PARTY-LICENSES: from the staged source tree"
else
    echo "--- THIRD-PARTY-LICENSES: cargo deny list"
    (cd "$SOURCE" && cargo deny list >THIRD-PARTY-LICENSES)
fi

SCOOTBG_VERSION=$(python3 "$META" versions --source "$SOURCE" | sed -n 's/^scootbg //p')
echo "--- versions: scoot/scootbg $SCOOTBG_VERSION (lockstep), scootbar $(
    python3 "$META" versions --source "$SOURCE" | sed -n 's/^scootbar //p')"

export CARGO_NET_OFFLINE=true
STAGE_ROOT="$OUT/stage"
rm -rf "$STAGE_ROOT"
mkdir -p "$OUT" "$STAGE_ROOT"
# Honor an outside CARGO_TARGET_DIR (CI sets one); default to the
# source tree's own target/ otherwise.
BINDIR="${CARGO_TARGET_DIR:-$SOURCE/target}/release"

for pkg in scoot scootbg scootbar; do
    echo "--- $pkg: cargo build --release --locked --offline -p $pkg"
    (cd "$SOURCE" && cargo build --release --locked --offline -p "$pkg")

    STAGE="$STAGE_ROOT/$pkg"
    mkdir -p "$STAGE/DEBIAN" "$STAGE/usr/bin" "$STAGE/usr/share/doc/$pkg"

    install -m755 "$BINDIR/$pkg" "$STAGE/usr/bin/$pkg"
    install -m644 "$SOURCE/THIRD-PARTY-LICENSES" "$STAGE/usr/share/doc/$pkg/THIRD-PARTY-LICENSES"

    # The license inventory's companion: the MIT grant itself plus what
    # is whose, so /usr/share/doc/<pkg>/copyright answers lintian's
    # no-copyright-file on its own.
    {
        echo "Upstream: scoot-sh/scoot (https://github.com/scoot-sh/scoot)"
        echo
        sed -n '1,12p' "$SOURCE/LICENSE"
        echo
        echo "scoot itself is MIT (above). Every third-party crate in the"
        echo "build is listed with its license in THIRD-PARTY-LICENSES"
        echo "(generated by 'cargo deny list' at packaging time); the full"
        echo "texts the inventory names (Smithay's MIT, others) are in"
        echo "NOTICE and the vendored sources."
        echo
        sed -n '1,8p' "$SOURCE/NOTICE"
    } >"$STAGE/usr/share/doc/$pkg/copyright"

    case "$pkg" in
        scoot)
            install -m755 "$SOURCE/resources/scoot-session" "$STAGE/usr/bin/scoot-session"
            install -Dm644 "$HERE/scoot.desktop" "$STAGE/usr/share/wayland-sessions/scoot.desktop"
            "$BINDIR/scoot" --print-default-config >"$STAGE/usr/share/doc/scoot/config.toml.example"
            install -m644 "$HERE/README.Debian.scoot" "$STAGE/usr/share/doc/scoot/README.Debian"
            ;;
        scootbar)
            install -Dm644 "$HERE/scootbar.service" "$STAGE/usr/lib/systemd/user/scootbar.service"
            install -m644 "$HERE/bar.toml.example" "$STAGE/usr/share/doc/scootbar/bar.toml.example"
            install -m644 "$HERE/README.Debian.scootbar" "$STAGE/usr/share/doc/scootbar/README.Debian"
            ;;
    esac

    # Derived, not remembered: shlibdeps versions, allow-list checked.
    # Only the binary: scoot-session is a shell script, and passing it
    # would only add a warning (it stays covered by inspection -- it
    # execs the compositor or degrades to it). dpkg-shlibdeps insists
    # on reading debian/control, so it gets a stub in the stage (real
    # metadata ships only in DEBIAN/control); the stub is removed
    # before dpkg-deb runs, never packaged.
    mkdir -p "$STAGE/debian"
    printf 'Source: %s\n\nPackage: %s\nArchitecture: %s\nDescription: shlibdeps stub\n' \
        "$pkg" "$pkg" "$ARCH" >"$STAGE/debian/control"
    if ! SHLIBS=$(cd "$STAGE" && dpkg-shlibdeps -O "usr/bin/$pkg" 2>"$OUT/shlibdeps-$pkg.log"); then
        echo "build-deb.sh: dpkg-shlibdeps failed for $pkg (log below)" >&2
        cat "$OUT/shlibdeps-$pkg.log" >&2
        exit 1
    fi
    rm -rf "$STAGE/debian"
    DEPENDS=$(python3 "$META" check-shlibdeps --package "$pkg" "$SHLIBS")
    echo "--- $pkg: Depends: $DEPENDS"

    python3 "$META" control --package "$pkg" --source "$SOURCE" \
        --arch "$ARCH" --depends "$DEPENDS" --revision "$REVISION" \
        --scootbg-version "$SCOOTBG_VERSION-$REVISION" \
        >"$STAGE/DEBIAN/control"

    VER=$(sed -n 's/^Version: //p' "$STAGE/DEBIAN/control")
    dpkg-deb --build "$STAGE" "$OUT/${pkg}_${VER}_${ARCH}.deb"
    ls -l "$OUT/${pkg}_${VER}_${ARCH}.deb"
done

echo "--- built:"
ls -l "$OUT"/*.deb
