# `programs.scoot.desktop.audio` for home-manager: PipeWire-adjacent
# scripts the keymap's volume, brightness and mic-mute binds run, the
# sink helper the future Bluetooth picker calls, and the OSD (wob on
# the `overlay` layer, themed by the look). The option shapes live in
# `./desktop.nix` (shared with the NixOS side); the `package` defaults
# live here because only this side has `pkgs`. See
# site/src/content/docs/desktop/index.md#sound-brightness-keys-and-the-on-screen-display.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.scoot;
  audio = cfg.desktop.audio;

  # The desktop profile's shared option subtree and look palettes (the
  # `enum` type guarantees the name, so the lookup cannot fail).
  desktop = import ./desktop.nix { inherit lib; };
  look = if cfg.desktop.look == null then null else desktop.looks.${cfg.desktop.look};
  themed = look != null && (cfg.desktop.theme.targets.osd.enable or true);

  # A `#rrggbb` look token as wob's `RRGGBBAA` (opaque: the OSD never
  # wants translucency -- text over a terminal needs the contrast).
  hexA = color: "${lib.removePrefix "#" color}ff";

  # The OSD's themed colors, from the same roles the bar, the locker
  # and the menus are themed from (one menu, one palette): the bar's
  # face for the background, the accent for the fill, the active ring
  # for the border. Past 100% (a `5%+` step past full) wob switches to
  # the overflow colors, so those are the urgent leaf -- over-amplified
  # reads as a warning, which is what it is. Muted is the same bar
  # washed out (the dim leaf), so mute reads at a glance.
  osdColors = {
    background = hexA look.barColors.background;
    bar = hexA look.barColors.accent;
    border = hexA look.appearance.focus_ring_active_color;
    overflowBar = hexA look.barColors.urgent;
    overflowBorder = hexA look.barColors.urgent;
    mutedBar = hexA look.barColors.dim;
    mutedBorder = hexA look.barColors.dim;
  };

  # The wob config file: always the geometry and the hide timeout (a
  # hidden OSD holds no surface and wakes nothing -- wob blocks in
  # `poll()` until the next value), plus the look's colors unless
  # unthemed or opted out (then wob's own black-and-white stands, and
  # the muted style is a fixed gray so `show ... muted` never names a
  # style the file does not define).
  osdIni = pkgs.writeText "wob-config" (
    lib.concatStringsSep "\n" (
      [
        "# Generated by programs.scoot.desktop.audio -- see https://www.scoot.sh/desktop/#sound-brightness-keys-and-the-on-screen-display."
        "timeout = ${toString audio.osd.timeoutMs}"
        "max = 100"
        "width = 400"
        "height = 40"
        "anchor = bottom"
        "margin = 48"
        "overflow_mode = nowrap"
      ]
      ++ lib.optionals themed [
        "background_color = ${osdColors.background}"
        "bar_color = ${osdColors.bar}"
        "border_color = ${osdColors.border}"
        "overflow_background_color = ${osdColors.background}"
        "overflow_bar_color = ${osdColors.overflowBar}"
        "overflow_border_color = ${osdColors.overflowBorder}"
        ""
        "[style.muted]"
        "background_color = ${osdColors.background}"
        "bar_color = ${osdColors.mutedBar}"
        "border_color = ${osdColors.mutedBorder}"
      ]
      ++ lib.optionals (!themed) [
        ""
        "[style.muted]"
        "background_color = 000000ff"
        "bar_color = 888888ff"
        "border_color = 888888ff"
      ]
    )
    + "\n"
  );

  # Absolute tool paths when the slot knows a package, bare names from
  # PATH otherwise (off Linux, or a direct-module setup without the
  # overlay): a missing tool then fails loudly in the script (its own
  # message on stderr, exit 1 -- never wedging input, since a bind is
  # one `spawn`), so the binds are always safe to render.
  binOr = name: pkg: if pkg != null then "${lib.getExe' pkg name}" else name;

  wpctlBin = binOr "wpctl" cfg.desktop.keys.volumePackage;
  brightnessBin = binOr "brightnessctl" cfg.desktop.keys.brightnessPackage;
  pwDumpBin = binOr "pw-dump" audio.dumpPackage;
  jqBin = lib.getExe pkgs.jq;
  awkBin = lib.getExe' pkgs.gawk "awk";
  tailBin = lib.getExe' pkgs.coreutils "tail";
  mkfifoBin = lib.getExe' pkgs.coreutils "mkfifo";

  # Where the OSD listens: the session runtime dir, so two logins never
  # share one (and a stale fifo from a dead session is simply never
  # read). Unit and scripts compute it the same way.
  fifoPath = "\${XDG_RUNTIME_DIR:-/run/user/\${UID}}/scoot-osd.fifo";

  # The OSD itself: `show <percent> [style]` feeds one value to the
  # daemon, `daemon` runs it (the user unit's `ExecStart`). One script,
  # so the pins name one derivation. The fifo open is read-write
  # (`<>`), which never blocks -- even with the daemon down the write
  # lands in the pipe buffer and shows (stale, then hides) when it
  # restarts, instead of wedging a held key's repeat at 25 Hz. A
  # missing fifo (the unit never ran) fails loud, not silent.
  scootOsd = pkgs.writeShellScriptBin "scoot-osd" ''
    fifo="${fifoPath}"
    case "''${1:-}" in
      show)
        case "''${2:-}" in
          "" | *[!0-9]*)
            echo "scoot-osd show: need a percent (got ''${2:-})" >&2
            exit 1
            ;;
        esac
        if [ ! -p "$fifo" ]; then
          echo "scoot-osd show: no OSD running at $fifo (is desktop.audio enabled?)" >&2
          exit 1
        fi
        if [ -n "''${3:-}" ]; then
          printf '%s %s\n' "$2" "$3" 3<> "$fifo" >&3
        else
          printf '%s\n' "$2" 3<> "$fifo" >&3
        fi
        ;;
      daemon)
        if [ ! -p "$fifo" ]; then
          ${mkfifoBin} -m 600 "$fifo"
        fi
        exec ${tailBin} -f "$fifo" | exec ${
          if audio.osd.package != null then lib.getExe audio.osd.package else "wob"
        } -c ${osdIni}
        ;;
      *)
        echo "usage: scoot-osd {show <percent> [style]|daemon}" >&2
        exit 1
        ;;
    esac
  '';

  # Volume and mic mute through `wpctl`, then the OSD: the step first
  # (so a failing control fails before anything shows), the level
  # after (so the bar shows what landed, including a `5%+` past 100 --
  # wob clamps it into the urgent overflow style). `sink-show` only
  # shows (what the sink switch calls after moving the default). A
  # control with no device behind it (headless, a VM, no server) fails
  # loud per entry: wpctl's own error plus exit 1. The `get-volume`
  # shapes are `Volume: 0.75`, `Volume: 1.05 [MUTED]` (fractions, no
  # percent sign -- 1.05 is 105%) or `Volume: 75%` where a server
  # prints percents.
  scootVolume = pkgs.writeShellScriptBin "scoot-volume" ''
    node="@DEFAULT_AUDIO_SINK@"
    cmd="''${1:-}"
    case "$cmd" in
      sink-up) ${wpctlBin} set-volume "$node" 5%+ || exit 1 ;;
      sink-down) ${wpctlBin} set-volume "$node" 5%- || exit 1 ;;
      sink-mute) ${wpctlBin} set-mute "$node" toggle || exit 1 ;;
      mic-mute)
        node="@DEFAULT_AUDIO_SOURCE@"
        ${wpctlBin} set-mute "$node" toggle || exit 1
        ;;
      sink-show) ;;
      *)
        echo "usage: scoot-volume {sink-up|sink-down|sink-mute|mic-mute|sink-show}" >&2
        exit 1
        ;;
    esac
    out="$(${wpctlBin} get-volume "$node" 2>&1)" || {
      echo "scoot-volume: no audio device for $node ($out)" >&2
      exit 1
    }
    vol="''${out#Volume: }"
    style=""
    case "$vol" in
      *" [MUTED]")
        vol="''${vol% \[MUTED]}"
        style="muted"
        ;;
    esac
    # `get-volume` prints a fraction (`0.75`, `1.05`) or a percent
    # (`75%`): anything else is a server we cannot parse, failed loud
    # rather than shown as a wrong number.
    case "$vol" in
      "" | *[!0-9.%]*)
        echo "scoot-volume: cannot parse the level from '$out'" >&2
        exit 1
        ;;
    esac
    case "$vol" in
      *%) vol="''${vol%\%}" ;;
      *) vol="$(${awkBin} -v v="$vol" 'BEGIN { printf "%d", v * 100 + 0.5 }')" ;;
    esac
    ${scootOsd}/bin/scoot-osd show "$vol" "$style" || echo "scoot-volume: the step landed, the OSD did not show" >&2
  '';

  # Brightness across every backlight device (laptop panel plus
  # externals: `brightnessctl -l` lists them, class `backlight` --
  # keyboard LEDs are class `leds` and stay alone, reserved and
  # unbound). Each device steps the same relative amount (`-e` keeps
  # the keymap's exponential curve), and the OSD shows the rounded
  # average -- one bar for the whole desk. No backlight device at all
  # (a VM, a headless box) fails loud, naming it.
  scootBrightness = pkgs.writeShellScriptBin "scoot-brightness" ''
    case "''${1:-}" in
      up) delta="+5%" ;;
      down) delta="5%-" ;;
      *)
        echo "usage: scoot-brightness {up|down}" >&2
        exit 1
        ;;
    esac
    devs="$(${brightnessBin} -c backlight -m -l 2>/dev/null | ${awkBin} -F, '$2 == "backlight" { print $1 }')"
    if [ -z "$devs" ]; then
      echo "scoot-brightness: no backlight devices (brightnessctl -c backlight -m -l is empty)" >&2
      exit 1
    fi
    for d in $devs; do
      ${brightnessBin} -e -d "$d" set "$delta" || {
        echo "scoot-brightness: stepping $d failed" >&2
        exit 1
      }
    done
    avg="$(${brightnessBin} -c backlight -m -l 2>/dev/null | ${awkBin} -F, '
      $2 == "backlight" { gsub(/%/, "", $4); sum += $4; n++ }
      END { if (n == 0) exit 1; printf "%d", sum / n + 0.5 }')" || {
      echo "scoot-brightness: reading the level back failed" >&2
      exit 1
    }
    ${scootOsd}/bin/scoot-osd show "$avg" || echo "scoot-brightness: the step landed, the OSD did not show" >&2
  '';

  # Sink switching without a picker (the Bluetooth picker in
  # `desktop-apps` calls this: `list` fills its menu, `set` runs the
  # pick). `pw-dump` is the stable source (PipeWire's own JSON:
  # `media.class == Audio/Sink`, named by `node.description` else
  # `node.name`); the current default comes from `wpctl inspect`
  # (`id 42, type ...` on the first line). No sinks, or no server,
  # fails loud; one sink cycles onto itself with a message.
  scootSink = pkgs.writeShellScriptBin "scoot-audio-sink" ''
    sinks="$(${pwDumpBin} 2>/dev/null | ${jqBin} -r '.[] | select(.info.props."media.class" == "Audio/Sink") | "\(.id) \(.info.props."node.description" // .info.props."node.name")"' 2>/dev/null)"
    if [ -z "$sinks" ]; then
      echo "scoot-audio-sink: no audio sinks (is PipeWire running?)" >&2
      exit 1
    fi
    case "''${1:-}" in
      list)
        printf '%s\n' "$sinks"
        ;;
      set)
        want="''${2:-}"
        if [ -z "$want" ]; then
          echo "usage: scoot-audio-sink set <id|name>" >&2
          exit 1
        fi
        id="$(printf '%s\n' "$sinks" | ${awkBin} -v want="$want" '
          { id = $1; $1 = ""; sub(/^ /, ""); if (id == want || $0 == want) { print id; found++ } }
          END { if (found == 1) exit 0; exit 1 }')" || {
          echo "scoot-audio-sink: no single sink matches '$want' (see: scoot-audio-sink list)" >&2
          exit 1
        }
        ${wpctlBin} set-default "$id" || exit 1
        name="$(printf '%s\n' "$sinks" | ${awkBin} -v id="$id" '$1 == id { $1 = ""; sub(/^ /, ""); print }')"
        # Diagnostics to stderr: `list` owns stdout (the picker
        # contract), everything else reports there.
        echo "Default sink: $name" >&2
        ${scootVolume}/bin/scoot-volume sink-show
        ;;
      cycle)
        current="$(${wpctlBin} inspect @DEFAULT_AUDIO_SINK@ 2>/dev/null | ${awkBin} '/^id / { gsub(/,/, "", $2); print $2; exit }')"
        if [ -z "$current" ]; then
          echo "scoot-audio-sink: cannot tell the current default sink" >&2
          exit 1
        fi
        next="$(printf '%s\n' "$sinks" | ${awkBin} -v cur="$current" '
          { ids[n++] = $1 }
          END {
            for (i = 0; i < n; i++) if (ids[i] == cur) { print ids[(i + 1) % n]; exit }
            print ids[0]
          }')"
        if [ "$next" = "$current" ]; then
          echo "scoot-audio-sink: only one sink, staying" >&2
        else
          ${wpctlBin} set-default "$next" || exit 1
        fi
        ${scootVolume}/bin/scoot-volume sink-show
        ;;
      *)
        echo "usage: scoot-audio-sink {list|set <id|name>|cycle}" >&2
        exit 1
        ;;
    esac
  '';

  audioScripts = [
    scootOsd
    scootVolume
    scootBrightness
    scootSink
  ];

  isLinux = pkgs.stdenv.hostPlatform.isLinux;
in
{
  options.programs.scoot.desktop.audio = {
    # The tools below are Linux-only: their attributes refuse
    # evaluation when forced on Darwin, so `or null` alone does not
    # save them (the Darwin `nix flake check` run reads every
    # default). Off Linux each defaults to null, which the assertions
    # below refuse loudly instead of installing nothing silently.
    osd.package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if isLinux then (if pkgs ? wob then pkgs.wob else null) else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.wob else null";
      description = ''
        The on-screen display to run the keymap's volume, brightness
        and mic-mute binds through (must take values on stdin and sit
        on the `overlay` layer, the way wob does). Null installs
        nothing. Linux-only: null off Linux.
      '';
    };

    dumpPackage = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if isLinux then (if pkgs ? pipewire then pkgs.pipewire else null) else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.pipewire else null";
      description = ''
        The PipeWire package whose `pw-dump` the sink helper lists
        sinks through. Null installs nothing. Linux-only: null off
        Linux.
      '';
    };

    # Internal wiring, not user options: the four scripts above, built
    # once here and read by the keymap (`keys-home.nix` routes the
    # volume, brightness and mic-mute binds through them while the
    # slot is on). Set unconditionally -- pure derivations, so they
    # evaluate everywhere (bare tool names off Linux) and are built
    # only where installed.
    scripts = lib.mkOption {
      type = lib.types.attrsOf lib.types.package;
      default = { };
      internal = true;
      visible = false;
      description = ''
        Internal: the audio slot's scripts (osd, volume, brightness,
        sink), read by the keymap. Not for direct use.
      '';
    };
  };

  config = lib.mkMerge [
    # The scripts, built once here for the keymap to read (see
    # `scripts` above): pure derivations, set without the slot so the
    # binds always have something to name.
    {
      programs.scoot.desktop.audio.scripts = {
        osd = scootOsd;
        volume = scootVolume;
        brightness = scootBrightness;
        sink = scootSink;
      };
    }

    (lib.mkIf audio.enable {
      assertions = [
        {
          assertion = audio.osd.package != null;
          message = ''
            programs.scoot.desktop.audio.enable is set but
            programs.scoot.desktop.audio.osd.package is null: set it
            explicitly (apply the overlay, or point at a wob).
          '';
        }
        {
          assertion = audio.dumpPackage != null;
          message = ''
            programs.scoot.desktop.audio.enable is set but
            programs.scoot.desktop.audio.dumpPackage is null: set it
            explicitly (apply the overlay, or point at a pipewire).
          '';
        }
        {
          assertion = audio.osd.timeoutMs >= 0;
          message = ''
            programs.scoot.desktop.audio.osd.timeoutMs is ${toString audio.osd.timeoutMs}:
            the hide timeout is 0 or more milliseconds.
          '';
        }
      ];

      # The OSD, its scripts and the sink helper's tools (Linux only:
      # the keymap renders the binds for the Linux box they deploy
      # to and installs nothing on Darwin, the way the slot scripts
      # do).
      home.packages =
        lib.optional (audio.osd.package != null) audio.osd.package ++ lib.optionals isLinux audioScripts;

      # The wob config, beside the unit that runs it. Pure text, so
      # it renders wherever the slot is on (like the swaylock config:
      # without the daemon beside it the file simply waits).
      xdg.configFile."wob/wob.ini".source = osdIni;

      # The OSD daemon: one wob on a fifo in the session runtime dir,
      # fed one `value [style]` line per key press. Wanted by
      # `scoot-session.target` -- scoot's own session scope (started by
      # the launcher past the display import) -- never the shared
      # `graphical-session.target`, which every other desktop reaches
      # too. Retried like the bar's unit rather than conditioned (a
      # skipped start is never retried). Hidden it holds no surface
      # and wakes nothing (measured: ~2.2 MB RSS, ~0 wakeups --
      # see site/src/content/docs/desktop/index.md#sound-brightness-keys-and-the-on-screen-display).
      # A null beside `enable` leaves the unit out (the loud assertion
      # above, not a throw inside `getExe`: the same guard the bar's
      # unit uses, since standalone evals collect assertions without
      # enforcing them).
      systemd.user.services.scoot-osd = lib.mkIf (isLinux && audio.osd.package != null) {
        Unit = {
          Description = "scoot on-screen display (wob: volume and brightness)";
          PartOf = [ "scoot-session.target" ];
          After = [ "scoot-session.target" ];
          # A new OSD script or config restarts the daemon (it starts
          # in milliseconds, and a stale fifo drains into the fresh
          # wob, which hides again after the timeout).
          X-Restart-Triggers = [
            "${scootOsd}"
            "${osdIni}"
          ];
          # Unending retries, like the bar's unit (`StartLimitIntervalSec`
          # lives in `[Unit]`: systemd ignores it in `[Service]`).
          StartLimitIntervalSec = 0;
        };
        Service = {
          ExecStart = "${scootOsd}/bin/scoot-osd daemon";
          Restart = "on-failure";
          RestartSec = 2;
        };
        Install.WantedBy = [ "scoot-session.target" ];
      };
    })

    # The profile turns the slot on (still individually disable-able
    # at plain priority, the way the clipboard slot works).
    (lib.mkIf cfg.desktop.enable {
      programs.scoot.desktop.audio.enable = lib.mkDefault true;
    })
  ];
}
