# `programs.scoot.desktop.capture` for home-manager: the screencast
# chooser config `xdg-desktop-portal-wlr` reads, and the tools the
# keymap's screenshot binds run. The option shapes live in
# `./desktop.nix` (shared with the NixOS side); the `package` defaults
# live here because only this side has `pkgs`. The portal backends
# themselves and PipeWire are the NixOS side's (`nixos.nix`): without
# it the chooser config still renders (a files-only setup for a Linux
# box), but nothing answers the cast. See
# site/src/content/docs/desktop/index.md#screenshots-and-screen-sharing.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.scoot;
  cap = cfg.desktop.capture;

  # The desktop profile's shared option subtree and look palettes (the
  # `enum` type guarantees the name, so the lookup cannot fail).
  desktop = import ./desktop.nix { inherit lib; };
  look = if cfg.desktop.look == null then null else desktop.looks.${cfg.desktop.look};
  themed = look != null && (cfg.desktop.theme.targets.capture.enable or true);

  # The chooser's and the region picker's theme: the look's roles the
  # same way the launcher and the history picker carry them (opaque
  # `rrggbbaa` for fuzzel, `#rrggbb` for slurp -- both spellings from
  # the same roles, so the three menus read as one). Nothing without
  # a look (or opted out): their own styles stand.
  fuzzelTheme = import ./fuzzel-theme.nix { inherit lib; };
  hexA = color: "${lib.removePrefix "#" color}ff";
  # Quoted: a bare `#rrggbb` would start a shell comment wherever
  # xdpw runs the chooser through a shell and eat the rest of the
  # line.
  hashA = color: "'#${hexA color}'";
  # slurp's dim (`-b`) stays its own default: an opaque themed dim
  # would hide the very screens the click picks between, so only the
  # border and the selection carry the look.
  slurpThemeFlags = lib.optionalString themed " -c ${hashA look.appearance.focus_ring_active_color} -s ${hashA look.barColors.accent}";
  fuzzelThemeFlags = if themed then fuzzelTheme look else "";

  # Absolute tool paths when the slot names packages, bare names from
  # PATH otherwise (off Linux, or a direct-module setup without the
  # overlay): a missing tool then fails quietly at runtime --
  # `State::spawn` warns and reports `false`, never wedging input --
  # so the binds are always safe to render.
  binOr = name: pkg: if pkg != null then "${lib.getExe' pkg name}" else name;

  grimBin = binOr "grim" cap.grimPackage;
  slurpBin = binOr "slurp" cap.slurpPackage;
  wlCopyBin = binOr "wl-copy" cap.wlClipboardPackage;
  menuBin = if cap.menuPackage != null then lib.getExe cap.menuPackage else "fuzzel";

  # The output chooser xdpw asks before each cast (see `chooser` in
  # `desktop.nix`): a dmenu list of outputs through the profile's
  # fuzzel (lines on stdin, the selection on stdout -- the same
  # `--dmenu` contract the clipboard picker and the launcher speak),
  # xdpw's own click-to-pick shape through slurp, or nothing at all.
  #
  # The fuzzel menu runs through a wrapper script beside the keymap's
  # launcher script (same pattern, same theming): xdpw reads its
  # config through inih, whose 200-character line limit would cut a
  # fully-flagged `chooser_cmd` mid-flag (seen live: fuzzel refused a
  # truncated `--selection-color` with no value and the cast died).
  # The script keeps the config line a bare store path; the theme
  # travels inside it, where no line limit applies.
  chooserScript = pkgs.writeShellScriptBin "scoot-screencast-chooser" ''
    exec ${menuBin} --dmenu --prompt='Share: '${fuzzelThemeFlags}
  '';
  chooserCmd =
    if cap.chooser == "fuzzel" then
      "${chooserScript}/bin/scoot-screencast-chooser"
    else if cap.chooser == "slurp" then
      "${slurpBin} -f 'Monitor: %o' -or${slurpThemeFlags}"
    else
      null;

  # The per-desktop file xdpw reads first
  # (`$XDG_CONFIG_HOME/xdg-desktop-portal-wlr/scoot`, ahead of the
  # plain `config` and both `/etc` fallbacks -- see
  # `xdg-desktop-portal-wlr(5)`): the chooser above, the frame cap,
  # and, with no picker, which output to cast. Written as text (not
  # the INI generator): the values carry single quotes xdpw parses
  # itself, the way its own man page writes them.
  chooserConfig = pkgs.writeText "xdg-desktop-portal-wlr-scoot" (
    lib.concatStringsSep "\n" (
      [
        "# Generated by programs.scoot.desktop.capture -- see https://www.scoot.sh/desktop/#screenshots-and-screen-sharing."
      ]
      ++ [ "[screencast]" ]
      ++
        lib.optional (cap.chooser != "none")
          "chooser_type=${if cap.chooser == "fuzzel" then "dmenu" else "simple"}"
      ++ lib.optional (chooserCmd != null) "chooser_cmd=${chooserCmd}"
      ++ lib.optional (cap.chooser == "none") "chooser_type=none"
      ++ lib.optional (cap.chooser == "none" && cap.outputName != null) "output_name=${cap.outputName}"
      ++ [ "max_fps=${toString cap.maxFps}" ]
    )
    + "\n"
  );

  isLinux = pkgs.stdenv.hostPlatform.isLinux;
in
{
  options.programs.scoot.desktop.capture = {
    # The tools below are Linux-only: their attributes refuse
    # evaluation when forced on Darwin, so `or null` alone does not
    # save them (the Darwin `nix flake check` run reads every
    # default). Off Linux each defaults to null, which the assertions
    # below refuse loudly instead of installing nothing silently.
    grimPackage = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if isLinux then (if pkgs ? grim then pkgs.grim else null) else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.grim else null";
      description = ''
        The screenshot tool the capture binds run and the portal's
        Screenshot backend shells out to (1.5.0 or later: older grim
        speaks only the wlr screencopy protocol scoot omits on
        purpose). Null installs nothing. Linux-only: null off Linux.
      '';
    };

    slurpPackage = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if isLinux then (if pkgs ? slurp then pkgs.slurp else null) else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.slurp else null";
      description = ''
        The region picker the region binds run (and the click picker
        behind `chooser = "slurp"`). Null installs nothing.
        Linux-only: null off Linux.
      '';
    };

    menuPackage = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if isLinux then (if pkgs ? fuzzel then pkgs.fuzzel else null) else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.fuzzel else null";
      description = ''
        The dmenu-style menu the output chooser runs
        (`fuzzel --dmenu`, themed by the look -- the launcher, which
        reuses this same package). Read only with
        `chooser = "fuzzel"`. Null installs nothing. Linux-only:
        null off Linux.
      '';
    };

    wlClipboardPackage = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if isLinux then (if pkgs ? wl-clipboard then pkgs.wl-clipboard else null) else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.wl-clipboard else null";
      description = ''
        The copy tool the clipboard screenshot bind runs (`wl-copy`
        on PATH beside the clipboard slot's own). Null installs
        nothing. Linux-only: null off Linux.
      '';
    };
  };

  config = lib.mkMerge [
    (lib.mkIf cap.enable {
      assertions = [
        {
          assertion = cap.grimPackage != null;
          message = ''
            programs.scoot.desktop.capture.enable is set but
            programs.scoot.desktop.capture.grimPackage is null: set it
            explicitly (apply the overlay, or point at a grim 1.5.0 or
            later).
          '';
        }
        {
          # Loud at eval, not a cast that binds nothing: older grim
          # speaks only `wlr-screencopy`, the protocol scoot omits on
          # purpose, so its captures fail every time.
          assertion = cap.grimPackage == null || lib.versionAtLeast (cap.grimPackage.version or "0") "1.5.0";
          message = ''
            programs.scoot.desktop.capture.grimPackage is too old
            (need 1.5.0 or later): only grim 1.5.0 or later speaks
            ext-image-copy-capture, which is what scoot serves.
          '';
        }
        {
          assertion = cap.slurpPackage != null;
          message = ''
            programs.scoot.desktop.capture.enable is set but
            programs.scoot.desktop.capture.slurpPackage is null: set
            it explicitly (apply the overlay, or point at a slurp).
          '';
        }
        {
          assertion = cap.chooser != "fuzzel" || cap.menuPackage != null;
          message = ''
            programs.scoot.desktop.capture.chooser is "fuzzel" but
            programs.scoot.desktop.capture.menuPackage is null: set it
            explicitly (apply the overlay, or point at a fuzzel).
          '';
        }
        {
          assertion = cap.wlClipboardPackage != null;
          message = ''
            programs.scoot.desktop.capture.enable is set but
            programs.scoot.desktop.capture.wlClipboardPackage is null:
            set it explicitly (apply the overlay, or point at a
            wl-clipboard).
          '';
        }
        {
          assertion = cap.maxFps >= 0;
          message = ''
            programs.scoot.desktop.capture.maxFps is ${toString cap.maxFps}:
            the frame cap is 0 (no limit) or more.
          '';
        }
        {
          # A fixed output names a connector (`wayland-info` lists
          # them); an empty one would render `output_name=` and cast
          # nothing, so it fails here instead.
          assertion = cap.chooser != "none" || cap.outputName != "";
          message = ''
            programs.scoot.desktop.capture.outputName is empty: name
            the output to cast (e.g. "eDP-1"), or leave it null to
            cast any output.
          '';
        }
      ];

      home.packages =
        lib.optional (cap.grimPackage != null) cap.grimPackage
        ++ lib.optional (cap.slurpPackage != null) cap.slurpPackage
        ++ lib.optional (cap.menuPackage != null) cap.menuPackage
        ++ lib.optional (cap.wlClipboardPackage != null) cap.wlClipboardPackage;

      # The per-desktop chooser file: a plain file (not a unit --
      # xdpw starts on demand over D-Bus and holds nothing until a
      # cast asks). Renders wherever the slot is on, including a
      # files-only setup for the Linux box it deploys to.
      xdg.configFile."xdg-desktop-portal-wlr/scoot".source = chooserConfig;
    })

    # The profile turns the slot on (still individually disable-able
    # at plain priority, the way the clipboard slot works).
    (lib.mkIf cfg.desktop.enable {
      programs.scoot.desktop.capture.enable = lib.mkDefault true;
    })
  ];
}
