# `programs.scoot.desktop.idle` for home-manager: the swayidle user
# unit, the audio inhibitor, and the swaylock config behind the lock
# event. The option shapes live in `./desktop.nix` (shared with the NixOS
# side); the `package`/`command` defaults live here because only this side
# has `pkgs`. See site/src/content/docs/desktop/index.md#idle-and-lock ("Idle and lock").
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.scoot;
  idle = cfg.desktop.idle;

  # The desktop profile's shared option subtree and the one helper
  # that reads look-derived values (never hand-mapped here).
  themeLook = import ./theme-look.nix { inherit lib; };
  look = themeLook.lookFor cfg.desktop;
  themed = themeLook.themed cfg.desktop "lock";

  # A `#rrggbb` look token as swaylock's `rrggbb` (its parser also takes
  # a leading `#` and an alpha pair, but the looks are opaque hex).
  hex = themeLook.noHash;

  # The locker's themed leaves: screen and indicator from the look's
  # roles (backgrounds, ring, accent, urgent), each overridable through
  # `lock.settings` below. `hover` exists only on some looks, so the
  # cleared state falls back to the accent.
  lockTheme = lib.mapAttrs (name: color: hex color) {
    color = look.appearance.background_color;
    inside-color = look.barColors.background;
    ring-color = look.appearance.focus_ring_active_color;
    ring-ver-color = look.barColors.accent;
    ring-clear-color = look.barColors.hover or look.barColors.accent;
    ring-wrong-color = look.barColors.urgent;
    inside-ver-color = look.barColors.accent;
    inside-clear-color = look.barColors.hover or look.barColors.accent;
    inside-wrong-color = look.barColors.urgent;
    key-hl-color = look.barColors.accent;
    bs-hl-color = look.barColors.accent;
    text-color = look.barColors.foreground;
    line-color = look.appearance.focus_ring_inactive_color;
    separator-color = look.appearance.focus_ring_inactive_color;
  };

  # swaylock reads `key=value` lines (`#` comments, blank lines
  # skipped; a bare word is a flag), so a merged attrset renders
  # directly. `lock.settings` wins per key; without a look (or opted
  # out) only those render, over swaylock's own defaults.
  swaylockConfig = pkgs.writeText "swaylock-config" (
    lib.concatStringsSep "\n" (
      [
        "# Generated by programs.scoot.desktop.idle.lock -- see https://www.scoot.sh/desktop/#idle-and-lock."
      ]
      ++ lib.mapAttrsToList (name: value: if value == "" then name else "${name}=${value}") (
        (lib.optionalAttrs themed lockTheme) // idle.lock.settings
      )
    )
    + "\n"
  );

  # The lock action is also the keymap's `super+escape` bind (see
  # `keys-home.nix`): with the keymap on and that bind kept, an
  # empty/quote-carrying command renders there even while the idle
  # policy is off -- so the refusal below fires then too, not just
  # beside the swayidle timeout line.
  lockCommandConsumed =
    (idle.enable && idle.lock.enable)
    || ((cfg.desktop.keys.enable or false) && (cfg.desktop.keys.binds.lock.enable or true));

  # Every tool present (a null beside `enable` is the loud assertion
  # below, not a throw inside `getExe`: the same guard the bar's unit
  # uses, since standalone evals collect assertions without enforcing
  # them).
  toolsReady =
    idle.package != null
    && idle.dimPackage != null
    && idle.offPackage != null
    && (!idle.lock.enable || idle.lock.package != null);

  lockerCmd = "${lib.getExe idle.lock.package} -f -C ${swaylockConfig}";

  # The clipboard wipe on the lock boundary (clear-on-lock): the history
  # db emptied as the session locks, so pre-lock copies never sit on
  # disk behind the lock screen -- while the store entry's own guard
  # (see `clipboard-home.nix`) keeps anything copied during the lock out
  # of the history. Runs before the locker on both lock paths (logind's
  # Lock through the `lock` event, and suspend through `before-sleep`,
  # which bypasses that signal); `;` keeps the locker running even if
  # the wipe fails. Only while the clipboard slot is on with a manager
  # to wipe with (the refusal for a null beside `enable` is the
  # clipboard child's own assertion); without the idle policy there is
  # no lock event to ride, so a standalone clipboard documents `wipe`
  # as manual instead (see site/src/content/docs/desktop/index.md#clipboard).
  clip = cfg.desktop.clipboard;
  clipWipeReady = clip.enable && clip.managerPackage != null;
  clipWipe = lib.optionalString clipWipeReady (
    "${if clip.managerPackage != null then lib.getExe' clip.managerPackage "cliphist" else "cliphist"}"
    + lib.optionalString (clip.dbPath != null) " -db-path '${clip.dbPath}'"
    + " wipe; "
  );

  # With display profiles on, the resume re-applies the matched one
  # after lighting every screen: `--on "*"` also lights an output the
  # profile disables (a clamshell panel), and nothing else would tell
  # the watcher. `;`, so a watcher failure never stops the screens
  # coming back on. The watcher serializes with its own hotplug
  # applies (one lock), and swayidle's `-w` waits for it -- an apply is
  # a handful of IPC calls.
  displaysWatcher = cfg.desktop.displays.watcher or null;
  displaysResume = lib.optionalString (
    displaysWatcher != null
  ) "; ${lib.getExe' displaysWatcher "scoot-displays"} apply";

  # swayidle parses each config line with wordexp (shell quoting), and
  # each command must be ONE quoted word: `sh -c` runs it, and the `"*"`
  # stays quoted so the shell never globs it into filenames (the same
  # reason the hand recipe in site/src/content/docs/scoot/configure.md#idle-locking-and-screen-power backslashes its
  # star). A 0 timeout omits its line (that step is off).
  swayidleConfig = pkgs.writeText "swayidle-config" (
    lib.concatStringsSep "\n" (
      [ "# Generated by programs.scoot.desktop.idle -- see https://www.scoot.sh/desktop/." ]
      ++ lib.optional (idle.dimTimeout != 0) (
        "timeout ${toString idle.dimTimeout} '${lib.getExe idle.dimPackage} -s set ${toString idle.dimLevel}%'"
        + " resume '${lib.getExe idle.dimPackage} -r'"
      )
      ++ lib.optional (
        idle.lock.enable && idle.lockTimeout != 0
      ) "timeout ${toString idle.lockTimeout} '${idle.lock.command}'"
      ++ lib.optional (idle.offTimeout != 0) (
        "timeout ${toString idle.offTimeout} '${lib.getExe idle.offPackage} --off \"*\"'"
        + " resume '${lib.getExe idle.offPackage} --on \"*\"${displaysResume}'"
      )
      # Before sleep the locker runs directly (not through
      # `lock.command`), so `-w` waits for the lock before logind
      # sleeps: `loginctl` returns once it signals, which would release
      # the sleep inhibitor before the locker is up.
      ++ lib.optional idle.lock.enable "before-sleep '${clipWipe}${lockerCmd}'"
      # Every path -- timeout, lid, manual `lock.command`, before-sleep
      # -- lands here through logind's Lock, which the locker's `lock` event listens on.
      ++ lib.optional idle.lock.enable "lock '${clipWipe}${lockerCmd}'"
    )
    + "\n"
  );
in
{
  options.programs.scoot.desktop.idle = {
    # The tools below are Linux-only: their attributes exist on Darwin
    # but refuse evaluation when forced, so `or null` alone does not
    # save them (the Darwin `nix flake check` run reads every default).
    # Off Linux each defaults to null, which the assertions below
    # refuse loudly instead of installing nothing silently.
    package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if pkgs.stdenv.hostPlatform.isLinux then pkgs.swayidle or null else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.swayidle or null else null";
      description = ''
        The swayidle package to run the idle policy from. Null installs
        nothing (set it explicitly without the overlay). Linux-only:
        null off Linux.
      '';
    };

    dimPackage = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if pkgs.stdenv.hostPlatform.isLinux then pkgs.brightnessctl or null else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.brightnessctl or null else null";
      description = ''
        The backlight tool the dim step runs (`-s set <level>%`, `-r`
        to restore). Needs the session's seat rights (logind grants the
        active login backlight access; over ssh, or with no seat, the
        step logs EPERM and does nothing) -- see site/src/content/docs/desktop/index.md#idle-and-lock.
        Linux-only: null off Linux.
      '';
    };

    offPackage = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if pkgs.stdenv.hostPlatform.isLinux then pkgs.wlopm or null else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.wlopm or null else null";
      description = ''
        The output-power tool the screens-off step runs (`--off "*"`
        for every output, `--on "*"` to wake). Linux-only: null off
        Linux.
      '';
    };

    mediaInhibit.package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if pkgs.stdenv.hostPlatform.isLinux then pkgs.sway-audio-idle-inhibit or null else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.sway-audio-idle-inhibit or null else null";
      description = ''
        The audio inhibitor to hold idle while media plays (any sink or
        source running). Linux-only: null off Linux.
      '';
    };

    lock = {
      package = lib.mkOption {
        type = lib.types.nullOr lib.types.package;
        default = if pkgs.stdenv.hostPlatform.isLinux then pkgs.swaylock or null else null;
        defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.swaylock or null else null";
        description = ''
          The locker package behind `daemon` (must speak its flags).
          Null installs nothing. Linux-only: null off Linux.
        '';
      };

      command = lib.mkOption {
        type = lib.types.str;
        default =
          if pkgs.stdenv.hostPlatform.isLinux then
            "${lib.getExe' pkgs.systemd "loginctl"} lock-session"
          else
            "loginctl lock-session";
        defaultText = lib.literalExpression ''if pkgs.stdenv.hostPlatform.isLinux then "''${lib.getExe' pkgs.systemd "loginctl"} lock-session" else "loginctl lock-session"'';
        example = "loginctl lock-session";
        description = ''
          The stable lock action: what the idle timeout runs, and what
          the keymap's `Super+Escape` bind runs (see
          `keys-home.nix`) -- lid-close and manual locks share this path through
          logind, which the locker's `lock` event listens on. An
          absolute store path by default, so user units never depend on
          PATH; a bare `loginctl lock-session` works wherever logind
          does. Off Linux the default is that bare form (logind itself
          is Linux-only, so the store path would refuse evaluation).
        '';
      };
    };
  };

  config = lib.mkMerge [
    # The policy: its tools, its config file, and the unit that runs
    # it. Wanted by `scoot-session.target` -- scoot's own session scope
    # (started by the launcher past the display import, so the display
    # is there when swayidle starts) -- never the shared
    # `graphical-session.target`, which every other desktop reaches too
    # and would start this policy inside someone else's session.
    # Retried like the bar's unit rather than conditioned (a skipped
    # start is never retried).
    (lib.mkIf idle.enable {
      assertions = [
        {
          assertion = idle.package != null;
          message = ''
            programs.scoot.desktop.idle.enable is set but
            programs.scoot.desktop.idle.package is null: set it
            explicitly (apply the overlay, or point at a swayidle).
          '';
        }
        {
          assertion = idle.dimPackage != null;
          message = ''
            programs.scoot.desktop.idle.enable is set but
            programs.scoot.desktop.idle.dimPackage is null: set it
            explicitly.
          '';
        }
        {
          assertion = idle.offPackage != null;
          message = ''
            programs.scoot.desktop.idle.enable is set but
            programs.scoot.desktop.idle.offPackage is null: set it
            explicitly.
          '';
        }
        {
          assertion = idle.dimTimeout >= 0 && idle.lockTimeout >= 0 && idle.offTimeout >= 0;
          message = ''
            programs.scoot.desktop.idle timeouts are seconds of
            inactivity and must be 0 or more (0 disables that step).
          '';
        }
        {
          assertion = idle.dimTimeout == 0 || (idle.dimLevel >= 1 && idle.dimLevel <= 100);
          message = ''
            programs.scoot.desktop.idle.dimLevel is a brightness
            percent, 1 to 100: 0 would be a black panel on an unlocked
            session, which is what the screens-off step is for. (Only
            checked while the dim step is on: `dimTimeout = 0` leaves
            the level unread.)
          '';
        }
      ];

      home.packages =
        lib.optional (idle.package != null) idle.package
        ++ lib.optional (idle.dimPackage != null) idle.dimPackage
        ++ lib.optional (idle.offPackage != null) idle.offPackage
        ++ lib.optional (idle.lock.enable && idle.lock.package != null) idle.lock.package
        ++ lib.optional (
          idle.mediaInhibit.enable && idle.mediaInhibit.package != null
        ) idle.mediaInhibit.package;

      xdg.configFile."swayidle/config".source = lib.mkIf toolsReady swayidleConfig;

      systemd.user.services.scoot-idle = lib.mkIf toolsReady {
        Unit = {
          Description = "scoot idle policy (swayidle: dim, lock, screens off)";
          PartOf = [ "scoot-session.target" ];
          After = [ "scoot-session.target" ];
          # New timeouts restart the daemon (it starts in milliseconds).
          X-Restart-Triggers = [ "${swayidleConfig}" ];
          # Unending retries, like the bar's unit (`StartLimitIntervalSec`
          # lives in `[Unit]`: systemd ignores it in `[Service]`).
          StartLimitIntervalSec = 0;
        };
        Service = {
          # `-w` waits for each command: the before-sleep lock is up
          # before logind sleeps (its delay inhibitor covers the wait).
          ExecStart = "${lib.getExe idle.package} -w -C ${swayidleConfig}";
          Restart = "on-failure";
          RestartSec = 2;
          # A start before the
          # compositor is up must retry, not die at the burst limit (a
          # broken config then logs every 2 s until fixed -- loud beats
          # silent).
        };
        Install.WantedBy = [ "scoot-session.target" ];
      };
    })

    # The inhibitor: its own unit beside the policy (no config file, so
    # no restart trigger -- a package change restarts the unit itself).
    (lib.mkIf (idle.enable && idle.mediaInhibit.enable) {
      assertions = [
        {
          assertion = idle.mediaInhibit.package != null;
          message = ''
            programs.scoot.desktop.idle.mediaInhibit.enable is set but
            programs.scoot.desktop.idle.mediaInhibit.package is null:
            set it explicitly.
          '';
        }
      ];

      systemd.user.services.scoot-audio-inhibit = lib.mkIf (idle.mediaInhibit.package != null) {
        Unit = {
          Description = "scoot idle inhibitor while audio plays";
          PartOf = [ "scoot-session.target" ];
          After = [ "scoot-session.target" ];
          # Unending retries (`StartLimitIntervalSec` lives in `[Unit]`:
          # systemd ignores it in `[Service]`).
          StartLimitIntervalSec = 0;
        };
        Service = {
          ExecStart = lib.getExe idle.mediaInhibit.package;
          Restart = "on-failure";
          RestartSec = 2;
        };
        Install.WantedBy = [ "scoot-session.target" ];
      };
    })

    # The locker's config file, beside the policy that runs it (kept in
    # its own element: with `lock.enable` off no locker file appears,
    # and the policy's lock lines stay out with it).
    (lib.mkIf (idle.enable && idle.lock.enable) {
      assertions = [
        {
          assertion = idle.lock.package != null;
          message = ''
            programs.scoot.desktop.idle.lock.enable is set but
            programs.scoot.desktop.idle.lock.package is null: set it
            explicitly (apply the overlay, or point at a locker that
            speaks the daemon's flags).
          '';
        }
      ];

      xdg.configFile."swaylock/config".source = swaylockConfig;
    })

    # The lock action's shape, wherever it renders (the swayidle
    # timeout line above, the keymap's `super+escape` bind): an
    # explicitly empty or whitespace-only value would run a no-op,
    # and a single quote would break out of the timeout line's
    # quoting and corrupt the config line. (`builtins.match`
    # returns null on no match, so each disjunct is false exactly
    # for empty/blank and quote-carrying strings.)
    (lib.mkIf lockCommandConsumed {
      assertions = [
        {
          assertion =
            builtins.match "^[[:space:]]*$" idle.lock.command == null
            && builtins.match ".*'.*" idle.lock.command == null;
          message = ''
            programs.scoot.desktop.idle.lock.command is empty, blank
            or contains a single quote: set the full lock action to run
            (e.g. `loginctl lock-session`).
          '';
        }
      ];
    })

    # The profile turns the policy on (each still individually
    # disable-able at plain priority, the way `session.enable` works on
    # the NixOS side).
    (lib.mkIf cfg.desktop.enable {
      programs.scoot.desktop.idle.enable = lib.mkDefault true;
      programs.scoot.desktop.idle.lock.enable = lib.mkDefault true;
      programs.scoot.desktop.idle.mediaInhibit.enable = lib.mkDefault true;
    })

    # Refusals that must fire whatever else is on (kept outside
    # `idle.enable` so they still fire then).
    (lib.mkIf idle.lock.enable {
      assertions = [
        {
          assertion = idle.enable;
          message = ''
            programs.scoot.desktop.idle.lock.enable needs
            programs.scoot.desktop.idle.enable: without the policy
            nothing listens for logind's Lock, and the locker would
            never start.
          '';
        }
      ];
    })
    (lib.mkIf idle.mediaInhibit.enable {
      assertions = [
        {
          assertion = idle.enable;
          message = ''
            programs.scoot.desktop.idle.mediaInhibit.enable needs
            programs.scoot.desktop.idle.enable: an inhibitor with no
            policy holds nothing off.
          '';
        }
      ];
    })
  ];
}
