# `programs.scoot.desktop.inputMethod` for home-manager: the fcitx5
# engine as a user unit, the toolkit variables where a toolkit still
# needs them, and the look's candidate-window theme. The option shapes
# live in `./desktop.nix` (shared with the NixOS side); the `package`
# default lives here because only this side has `pkgs`. See
# site/src/content/docs/desktop/index.md#input-method ("Input method").
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.scoot;
  im = cfg.desktop.inputMethod;

  # The desktop profile's shared option subtree and the one helper
  # that reads look-derived values (never hand-mapped here).
  themeLook = import ./theme-look.nix { inherit lib; };
  look = themeLook.lookFor cfg.desktop;
  themed = themeLook.themed cfg.desktop "inputMethod";

  isLinux = pkgs.stdenv.hostPlatform.isLinux;

  # A null beside `enable` is the loud assertion below, not a throw
  # inside `getExe`: the same guard the idle policy uses, since
  # standalone evals collect assertions without enforcing them.
  toolsReady = im.package != null;

  # The look as an fcitx5 classic UI theme (`scoot-look`, a name no
  # system theme takes -- fcitx5 reserves `default`/`default-dark`,
  # checked against its 5.1.21 `theme.cpp`). Sections mirror the
  # theme format (checked against fcitx5 5.1.21 `theme.h` and a
  # shipped theme): unselected text in the look's foreground, the
  # selected row in its accent with the background on top (the AA
  # pairing `theme-look.nix` measures for the bar: background on
  # accent passes everywhere the bar does), the input string in the
  # accent on the background. Anything this file leaves out keeps
  # fcitx5's own default (a partial theme loads over them). The `Sans`
  # faces resolve through fontconfig, so with the theme child's
  # `fonts` target they follow the look's UI sans.
  lookTheme = pkgs.writeText "scoot-look-theme.conf" ''
    # Generated by programs.scoot.desktop.inputMethod -- see https://www.scoot.sh/desktop/#input-method.
    [Metadata]
    Name=Scoot Look
    Version=1.0
    Author=scoot
    Description=The desktop look's palette as an fcitx5 classic UI theme.
    ScaleWithDPI=True

    [InputPanel]
    Font=Sans 11
    NormalColor=${look.barColors.foreground}
    HighlightColor=${look.barColors.accent}
    HighlightBackgroundColor=${look.barColors.background}
    HighlightCandidateColor=${look.barColors.background}

    [InputPanel/Background]
    Color=${look.barColors.background}
    BorderColor=${look.appearance.focus_ring_active_color}

    [InputPanel/Highlight]
    Color=${look.barColors.accent}

    [Menu]
    Font=Sans 10
    NormalColor=${look.barColors.foreground}

    [Menu/Background]
    Color=${look.barColors.background}

    [Menu/Highlight]
    Color=${look.barColors.accent}
  '';

  # The classic UI told to wear it. `Theme` is the name it loads
  # (checked against fcitx5 5.1.21 `classicui.h`: `Theme`, default
  # `default`); `DarkTheme` is what it loads when following the
  # system dark scheme (default `default-dark`) -- fcitx5 watches the
  # desktop portal's color-scheme for that, which the theme child
  # sets to `prefer-dark` under every dark look, so both names keep
  # either path themed. A partial file: every other classic UI key
  # keeps its default.
  classicUiConfig = pkgs.writeText "scoot-look-classicui.conf" ''
    # Generated by programs.scoot.desktop.inputMethod -- see https://www.scoot.sh/desktop/#input-method.
    Theme=scoot-look
    DarkTheme=scoot-look
  '';
in
{
  options.programs.scoot.desktop.inputMethod = {
    # The tool below is Linux-only: its attribute refuses evaluation
    # when forced on Darwin, so `or null` alone does not save it (the
    # Darwin `nix flake check` run reads every default). Off Linux it
    # defaults to null, which the assertion below refuses loudly
    # instead of installing nothing silently.
    package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = if isLinux then (if pkgs ? fcitx5 then pkgs.fcitx5 else null) else null;
      defaultText = lib.literalExpression "if pkgs.stdenv.hostPlatform.isLinux then pkgs.fcitx5 else null";
      description = ''
        The input-method engine to run (must speak
        `input-method-v2`: fcitx5's wayland frontend). Defaults to
        plain fcitx5 (keyboard layouts, compose and the XIM server,
        no CJK data -- add engines through `addons`). Null installs
        nothing. Linux-only: null off Linux.
      '';
    };
  };

  config = lib.mkMerge [
    # The engine: its package plus `addons` on PATH, and the unit that
    # runs it. Wanted by `scoot-session.target` -- scoot's own session
    # scope (started by the launcher past the display import, so the
    # display is there when the engine starts) -- never the shared
    # `graphical-session.target`, which every other desktop reaches too
    # and would start this engine inside someone else's session.
    # Retried like the bar's unit rather than conditioned (a skipped
    # start is never retried). The engine holds nothing periodic: no
    # polling here, no watchers -- it wakes on protocol events and
    # D-Bus calls only. A new theme restarts it (it starts in
    # milliseconds); anything else lands in `ExecStart` itself, so a
    # package change rewrites the unit and restarts it.
    (lib.mkIf im.enable {
      assertions = [
        {
          assertion = im.package != null;
          message = ''
            programs.scoot.desktop.inputMethod.enable is set but
            programs.scoot.desktop.inputMethod.package is null: set it
            explicitly (apply the overlay, or point at an fcitx5).
          '';
        }
      ];

      home.packages =
        lib.optional (im.package != null) im.package ++ im.addons;

      systemd.user.services.scoot-input-method = lib.mkIf toolsReady {
        Unit = {
          Description = "scoot input-method engine (fcitx5 over input-method-v2)";
          PartOf = [ "scoot-session.target" ];
          After = [ "scoot-session.target" ];
          # A new theme restarts the engine.
          X-Restart-Triggers = lib.optionals themed [
            "${lookTheme}"
            "${classicUiConfig}"
          ];
          # Unending retries, like the bar's unit (`StartLimitIntervalSec`
          # lives in `[Unit]`: systemd ignores it in `[Service]`).
          StartLimitIntervalSec = 0;
        };
        Service = {
          # An activation can arrive before the session reaches the
          # session target: skip cleanly then -- no restart -- and the
          # wanted-by below starts it with the display in the common case
          # (the same condition the mako unit uses).
          ExecCondition = "${lib.getExe' pkgs.bash "bash"} -c '[ -n \"$WAYLAND_DISPLAY\" ]'";
          ExecStart = "${lib.getExe im.package}";
          Restart = "on-failure";
          RestartSec = 2;
        };
        Install.WantedBy = [ "scoot-session.target" ];
      };

      # The toolkit variables, only where a toolkit still needs them
      # (checked against fcitx's own "Using Fcitx 5 on Wayland" plus
      # Qt 6.11.2's strings, which name both variables):
      # - `XMODIFIERS` for XWayland/X11 clients (XIM, unchanged under
      #   XWayland);
      # - `QT_IM_MODULE=fcitx` for Qt5 and older Qt6 (whose Wayland
      #   platform speaks only text-input-v2, which no compositor but
      #   KWin offers);
      # - `QT_IM_MODULES="wayland;fcitx"` for Qt 6.7 and later (newer
      #   Qt tries the native text-input first and falls back to the
      #   fcitx module, so the candidate popup stays compositor-placed
      #   where the toolkit allows it).
      # `GTK_IM_MODULE` deliberately stays unset: with it unset GTK3/4
      # use their Wayland text-input natively, which is the path the
      # compositor places the popup for (setting it to `fcitx` would
      # still work, but through the in-process popup). Each at
      # `mkDefault`, so an explicit value still wins; the manager file
      # (`environment.d` shape) reaches user units and D-Bus-activated
      # apps, the shell variables reach everything started from a
      # login shell.
      systemd.user.sessionVariables = {
        XMODIFIERS = lib.mkDefault "@im=fcitx";
        QT_IM_MODULE = lib.mkDefault "fcitx";
        QT_IM_MODULES = lib.mkDefault "wayland;fcitx";
      };
      home.sessionVariables = {
        XMODIFIERS = lib.mkDefault "@im=fcitx";
        QT_IM_MODULE = lib.mkDefault "fcitx";
        QT_IM_MODULES = lib.mkDefault "wayland;fcitx";
      };
    })

    # The look's candidate window, at `mkDefault` nowhere (files, not
    # values: opting the target out drops both files while the engine
    # keeps running). Without a look there is nothing to derive from,
    # so both stay out and fcitx5's own theme stands.
    (lib.mkIf (im.enable && themed && toolsReady) {
      xdg.dataFile."fcitx5/themes/scoot-look/theme.conf".source = lookTheme;
      xdg.configFile."fcitx5/conf/classicui.conf".source = classicUiConfig;
    })
  ];
}
